### ISSUE TITLE
Что нужно в ветке master хранить? 

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/AutoNetChallenge#1]

**Comment by KaiL4eK** [comment]
Пускай мастер будет основной веткой, просто льем туда, когда фича / модуль готовы

**Comment by KaiL4eK** [comment]
Либо можно master удалить, а develop сделать основной)

**Comment by KaiL4eK** [comment]
Так как вся работа пошла в develop, то предлагаю мастера сносить =)

**Comment by serykhelena** [comment]
Сделано (=
