### ISSUE TITLE
Структура для параметров ПИД-регуляторов

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/AutoNetChallenge#12]
Реализована структура для модуля `drive_cs.c`, нужно разобраться как её правильно объявить, чтобы Егор мог до неё добраться

**Comment by KaiL4eK** [comment]
В данном случае не Егор будет добираться до нее, а из ROS будет приходить инфа об установке нового набора параметров. Думаю, можно сделать функцию, аргумент которой является структурой с набором параметров, а модуль ROS будет ею пользовать при приходе новой инфы

**Comment by serykhelena** [comment]
Пока что закрываю, пользовать функции можно будет после настройки СУ по скорости
