### ISSUE TITLE
Не работает launch файл gz_localization_view

### ISSUE THREAD

**Issue by PonomarevDA** [serykhelena/AutoNetChallenge#18]
Тестирую launch файл `gz_localization_view` из пакета wr8_software.
Скрипт запускается, все узлы тоже, начало работы не предвещает беды.
Но в какой-то момент все ломается: иногда раньше, иногда позже.
По ссылке видео с логами терминала от начала до конца. Проблема возникает в середине видео.
https://youtu.be/t0RAa0YhLrE
Привожу часть логов, которые видны на видео:
```
[ WARN] [1569236226.354755274, 193.566000000]: Costmap2DROS transform timeout. Current time: 193.5660, global_pose stamp: 191.5500, tolerance: 2.0000
[ WARN] [1569236226.354871985, 193.566000000]: Could not get robot pose, cancelling reconfiguration
[ WARN] [1569236226.573027750, 193.696000000]: Transform timeout for global_costmap. Current time: 193.6960, pose stamp: 191.6860, tolerance: 2.0000
[ WARN] [1569236226.901645078, 193.903000000]: Unable to get starting pose of robot, unable to create global plan
...
[ WARN] [1569236274.706857127, 223.701000000]: TebLocalPlannerROS: trajectory is not feasible. Resetting planner...
...
[ERROR] [1569236288.296048840, 234.292000000]: Failed to get a plan.
[ERROR] [1569236288.528671402, 234.491000000]: Aborting because a valid plan could not be found. Even after executing all recovery behaviors
```

В чем причина ошибок локализации пока не понимаю, почитаю про cost map подробнее.

**Comment by PonomarevDA** [comment]
Замечу, что gz_slam_view.launch в принципе работает.

**Comment by PonomarevDA** [comment]
Почитал ros форумы на счет этой проблемы. 
1. [Costmap2DROS transform timeout](https://answers.ros.org/question/215256/costmap2dros-transform-timeout/)
2. [Costmap2DROS transform timeout.Could not get robot pose, cancelling reconfiguration](https://answers.ros.org/question/227638/costmap2dros-transform-timeoutcould-not-get-robot-pose-cancelling-reconfiguration/)

Решения я там никакого не нашел, но люди пишут, что процессор не успевает выполнять вычисления. По факту, как видно из `tf_monitor` или `view_frames`, с момента указания цели роботу, данные действительно начинают устаревать. Когда данные устаревают больше, чем значение tolerance, появляются warnings, а затем работа планера накрывается.

Отличие localization от slam лишь в том, что вместо `mapping_algorithm` появился `amcl`. Это наталкивает на мысль о том, что, в предположении, что процессор действительно не справляется, именно узлы скрипта `amcl.launch` максимально нагружают процессор. К слову, такие же выводы следуют из анализа графа, полученного из `view_frames`.

Короче, покрутив параметры `amcl.launch`, заметил, что `max_particles` оказывает прямое влияние на требуемую вычислительную способность процессора.
Одновременно запускал `view_frames` и указывал цель роботу при разных `max_particles`:
`max_particles` = 1000, delay = 0, [frames500_1000.pdf](https://github.com/lsd-maddrive/zaWRka-project/files/3648924/frames500_1000.pdf) (локализация работает хорошо)
`max_particles` = 2000, delay = 0, [frames500_2000.pdf](https://github.com/lsd-maddrive/zaWRka-project/files/3648926/frames500_2000.pdf) (с первого взгляда работает, но если покатать подольше, то тоже накрывается)
`max_particles` = 3000, delay = 2.45, [frames500_3000.pdf](https://github.com/lsd-maddrive/zaWRka-project/files/3648930/frames500_3000.pdf) (работа планера накрывается)
`max_particles` = 5000, delay = 4.3 сек, [frames500_5000.pdf](https://github.com/lsd-maddrive/zaWRka-project/files/3648931/frames500_5000.pdf) (работа планера накрывается очень быстро)

В итоге, сейчас при `max_particles` = 1000 все работает, багов при локализации пока не нашел.

**Comment by KaiL4eK** [comment]
Так значит закрываем issue?)
