### ISSUE TITLE
Проблема в понимании блока одометрии

### ISSUE THREAD

**Issue by serykhelena** [serykhelena/AutoNetChallenge#2]
В ветке encoder добавила файлы для работы с энкодером и одометрией. 
В энкодере работает таймер с периодом 1 секунда, получается скорость. 
Дальше скорость в м/с (взято как пример) передаётся в аргументы функций одометром, где происходит типа интегрирование теты, х и у. 
Результаты странные. 

Есть мысль, что есть косяки в понимании математики процесса.

**Comment by serykhelena** [comment]
@KaiL4eK , подправила модуль одометрии, можешь провести ревизию по возможности. Для тестов жду, когда освободится STM-ка

**Comment by KaiL4eK** [comment]
Воу, так ты объединила энкодер и одометрию?

**Comment by serykhelena** [comment]
@KaiL4eK, я может быть неправильно поняла, но в предыдущем сообщении договорились, что я использую один таймер для всего, поэтому я объединила. Но не могу сказать, что это удобно. Слишком много всего в одном файле.

**Comment by KaiL4eK** [comment]
Здесь можно сделать так, чтобы таймер был только в одометрии, а энкодер рассчитывал значние скорости только по запросу (вызову функции get). Или просто расчет переложить на блок одометрии, а от энкодера требуется лишь отдавать нынешнее пройденное расстояние

**Comment by KaiL4eK** [comment]
Для расчета скорости в одометрии можно брать предыдущий пройденный путь и нынешний

**Comment by serykhelena** [comment]
Пока промежуточное понимание получено, в будущем если что открою новую issue ^_______^
