### ISSUE TITLE
[Объявление] Система переведена на режим tickless

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/AutoNetChallenge#4]
В chconf.h мы перешли на режим tickless, частота RT стала 100кГц, таймер, используемый для RT 32битный, 5й, это требование режима tickless.
Тебе стоит ожидать, что функция получения системного времени будет выдавать большие значения)
Просто оповещение, как прочитаешь, закрывай =)

**Comment by serykhelena** [comment]
Прочитано, вроде даже понято (=
