### ISSUE TITLE
Find way to set initial pose for hector_mapping/gmapping

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/AutoNetChallenge#43]

**Comment by PonomarevDA** [comment]
It seems that the only way to set the initial pose is to pub it to the `/initialpose` topic from some node.
In localization we can use param `initial_pose_` in `amcl.launch`, but I can't find smth similar in SLAM.

**Comment by KaiL4eK** [comment]
Let`s try two ways (in priority):
- latched publication to /intialpose
- new TF (odom - map_odom)
