### ISSUE TITLE
Research google cartographer

### ISSUE THREAD

**Issue by KaiL4eK** [serykhelena/AutoNetChallenge#47]
https://google-cartographer.readthedocs.io/en/latest/

**Comment by Nikolaj37** [comment]
Основное отличие Google cartographer-а от hector slam-а - это наличие сильной библиотека для проектов с 3D маппированием по стереокамере, как основного источника данных. В 2D режиме нужно проверять на симуляции для моделей. Я могу попробовать протестировать обе системы в симуляции на одной карте и будет виднее.

**Comment by Nikolaj37** [comment]
После установки Google cartographer перестал работать xacro:

RLException: while processing /home/nikolay/catkin_ws/src/zaWRka-project/wr8_description/launch/gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: no such command [/home/nikolay/catkin_ws/src/xacro/xacro '/home/nikolay/catkin_ws/src/zaWRka-project/wr8_description/urdf/model.urdf.xacro' enable_stereo:=false]. 

Param xml is <param command="$(find xacro)/xacro '$(arg urdf_file)' enable_stereo:=$(arg enable_stereo)" name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by Nikolaj37** [comment]
Пробую установить google_cartographer, но возник следующий баг.
```
Could not find a package configuration file provided by
  "message_generation" with any of the following names:
    message_generationConfig.cmake
    message_generation-config.cmake
```
При этом пакет установлен, НО у него действительно нет -config.cmake файла в его директории.
```
nikolay@SeaWolf:/opt/ros/melodic/share/message_generation/cmake$ ls
message_generationConfig.cmake  message_generationConfig-version.cmake
```
Схожая проблема есть и у других пользователей cartographer-а(как показало гугление), но решения проблемы, увы, нет.

**Comment by Nikolaj37** [comment]
Есть серьёзная проблема, которая ограничивает применимость google_cartographer-а для проекта заварки - это разные версии protobuf-а. Gazebo использует 2.7, а google cartographer 3.4.0. Наличие более старой версии protobuf-а рушит сборку cartographer-а и наоборот. Это оставляет для симуляции только rviz, которого должно быть достаточно, но...

**Comment by Nikolaj37** [comment]
Установка google cartographer 
```
bash
cd catkin_ws
sudo apt-get update
sudo apt-get install -y python-wstool python-rosdep ninja-build
mkdir cartographer_ws
cd cartographer_ws
wstool init src
wstool merge -t src https://raw.githubusercontent.com/googlecartographer/cartographer_ros/master/cartographer_ros.rosinstall
wstool update -t src
src/cartographer/scripts/install_proto3.sh
rosdep update
rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y
#Build and install.
catkin_make_isolated --install --use-ninja

прописать в .bashrc
. ~/catkin_ws/cartographer_ws/devel_isolated/setup.bash
```

**Comment by KaiL4eK** [comment]
```
sudo apt install liblua5.3-dev
```

**Comment by PonomarevDA** [comment]
> После установки Google cartographer перестал работать xacro:
> 
> RLException: while processing /home/nikolay/catkin_ws/src/zaWRka-project/wr8_description/launch/gazebo.launch:
> Invalid tag: Cannot load command parameter [robot_description]: no such command [/home/nikolay/catkin_ws/src/xacro/xacro '/home/nikolay/catkin_ws/src/zaWRka-project/wr8_description/urdf/model.urdf.xacro' enable_stereo:=false].
> 
> Param xml is
> The traceback for the exception was written to the log file

Предположу, что отсутствует пакет `defusedxml`.
Если проблема не решилась, попробуй:
```pip2 install defusedxml```
Мне при такой ошибке это помогло.

**Comment by KaiL4eK** [comment]
Пока закрываем из-за большого кол-ва проблем и низкого приоритета
